"""
LangGraph state definition for the neuroimaging multi-agent pipeline.
"""

from typing import Optional, TypedDict


class SegmentationResult(TypedDict):
    mask_path: str  # Path to saved binary mask PNG
    bbox: list  # [x1, y1, x2, y2] bounding box
    guided_image_path: str  # Original image with red bbox overlay (for MedGemma only)


class ClassificationResult(TypedDict):
    predicted_class: str
    confidence: float
    all_probs: dict  # class_name → probability


class BiomedCLIPResult(TypedDict):
    ranked_labels: list  # Sorted highest → lowest similarity
    scores: list  # Corresponding cosine similarities
    top_label: str
    top_score: float


class NeuroimagingState(TypedDict):
    # ── Input ─────────────────────────────────────────────────────────────────
    image_path: str   # Absolute path to the raw input scan; never mutated after initial_state
    task: str         # "binary_tumor" | "multiclass_tumor" | "ms" | "stroke"
    metadata: dict    # Optional clinical context passed in by the caller (modality, patient info, etc.)

    # ── Routing ───────────────────────────────────────────────────────────────
    # All four fields written by: triage_node
    routing_decision: Optional[str]  # Always the literal "full_workup" — hardcoded by both
                                     # triage nodes. All graphs are linear, so this gates
                                     # nothing; its only reader is the unwired legacy helper
                                     # route_from_triage(). Informational / for eval grouping
                                     # only. See that docstring in pipeline/nodes.py.
    routing_confidence: float        # MedGemma's self-reported confidence in its routing decision
    routing_reasoning: str           # Short human-readable explanation from MedGemma
    suspected_pathology: str         # MedGemma's initial pathology label before specialist tools run

    # ── MedGemma structured diagnosis outputs ────────────────────────────────
    # Three separate MedGemma inference passes, each with a different input image and prompt:
    medgemma_diagnosis: Optional[dict]       # Written by triage_node      — raw scan + system_prompt.txt
    medgemma_bbox_diagnosis: Optional[dict]  # Written by cnn_with_mask_node — SAM3 bbox overlay +
                                             # system_prompt_bbox.txt; None when SAM3 was skipped
    final_medgemma_diagnosis: Optional[dict] # Written by report_node       — evidence-fusion pass that
                                             # synthesises all tool outputs into the definitive diagnosis

    # ── Tool outputs ──────────────────────────────────────────────────────────
    segmentation_result: Optional[SegmentationResult]   # Written by sam3_node
    classification_result: Optional[ClassificationResult]  # Written by cnn_node; overwritten by
                                                            # cnn_with_mask_node if CNN hadn't run yet
    biomedclip_result: Optional[BiomedCLIPResult]       # Written by biomedclip_node
    explainability_result: Optional[dict]  # Written by explainability_node; keys: "gradcam_pp" and/or
                                           # "integrated_gradients" mapping to saved PNG paths
    saliency_sam3_iou: Optional[float]    # Written by explainability_node; IoU between the GradCAM++
                                          # heatmap (threshold 0.5) and SAM3 binary mask; None when SAM3
                                          # was skipped or produced an empty mask
    sam3_mask_empty: bool                 # Written by explainability_node; True when SAM3 ran but
                                          # predicted zero lesion pixels (valid for normal scans)

    # ── Final output ──────────────────────────────────────────────────────────
    final_report: Optional[str]       # Written by report_node; free-text synthesis generated by MedGemma
    final_predicted_class: Optional[str]  # Written by report_node; resolved in priority order:
                                          # final_medgemma_diagnosis → CNN → BiomedCLIP → suspected_pathology
    final_confidence: float           # Written by report_node; updated by verification_node; may be
                                      # penalised by low saliency_sam3_iou or MedGemma–CNN disagreement
    requires_human_review: bool       # Written by report_node or verification_node; when True the FHIR
                                      # DiagnosticReport status is set to "preliminary" instead of "final"
    verification_result: Optional[dict]  # Written by verification_node; MedGemma post-hoc check of the
                                         # CNN prediction against the Grad-CAM++ saliency map; None when
                                         # explainability was not run
    fhir_report: Optional[dict]       # Written by fhir_node; FHIR R4 DiagnosticReport resource dict

    # ── Agent Forest outputs ──────────────────────────────────────────────────
    # Written by forest_triage_node (System C). None in standard / debate pipelines.
    forest_votes: Optional[list]     # [{role, diagnosis_name, diagnosis_detailed, diagnosis_confidence}, ...]
    forest_consensus: Optional[dict] # {winner, winner_detailed, vote_counts, vote_fraction,
                                     #  confidence_weighted_confidence, dissent_rate, n_agents}

    # ── Multi-Agent Debate outputs ────────────────────────────────────────────
    # Written by debate_node (System B). None in standard / forest pipelines.
    debate_arguments: Optional[list]       # [{round, role, argument}, ...]
    debate_verdict: Optional[dict]         # {winner, winner_detailed, confidence, reason,
                                           #  round_changed, rounds_completed}
    debate_rounds_completed: Optional[int]

    # ── Diagnostics ───────────────────────────────────────────────────────────
    routing_path: list  # Append-only list; each node appends its own name on entry — used for
                        # evaluation reporting and debugging (never used for control flow)


def initial_state(
    image_path: str, task: str, metadata: dict = None
) -> NeuroimagingState:
    """Create a blank state for a new image."""
    return NeuroimagingState(
        image_path=image_path,
        task=task,
        metadata=metadata or {},
        routing_decision=None,
        routing_confidence=0.0,
        routing_reasoning="",
        suspected_pathology="",
        medgemma_diagnosis=None,
        medgemma_bbox_diagnosis=None,
        final_medgemma_diagnosis=None,
        segmentation_result=None,
        classification_result=None,
        biomedclip_result=None,
        explainability_result=None,
        saliency_sam3_iou=None,
        sam3_mask_empty=False,
        final_report=None,
        final_predicted_class=None,
        final_confidence=0.0,
        requires_human_review=False,
        verification_result=None,
        fhir_report=None,
        routing_path=[],
        forest_votes=None,
        forest_consensus=None,
        debate_arguments=None,
        debate_verdict=None,
        debate_rounds_completed=None,
    )
